---
title: "STA355 A1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning=FALSE}
prob1_data = scan("prob1-data.txt")
halfnormal <- function(x,tau=0.5,ylim) {
       sigma <- quantile(abs(x),probs=tau)/sqrt(qchisq(tau,1))
       n <- length(x)
       pp <- ppoints(n)
       qq <- sqrt(qchisq(pp,df=1))
# upper envelope
       upper <- sigma*(qq + 3*sqrt(pp*(1-pp))/(2*sqrt(n)*dnorm(qq)))
# lower envelope 
       lower <- sigma*(qq - 3*sqrt(pp*(1-pp))/(2*sqrt(n)*dnorm(qq)))
# add upper and lower envelopes to plot
       if (missing(ylim)) ylim <- c(0,max(c(upper,abs(x))))
       plot(qq,sort(abs(x)),
          xlab="Half Normal quantiles",ylab="ordered data",pch=20,
          ylim=ylim)
       lines(qq,lower,lty=3,lwd=3,col="red")
       lines(qq,upper,lty=3,lwd=3,col="red")
       abline(a=0,b=sigma,lwd=3)
}

halfnormal(prob1_data)
```

```{r}
kevlar = read.table("kevlar.txt")
x = kevlar$V1
x = sort(x)
n = length(x)
d = c(n:1)*c(x[1],diff(x))
plot(c(1:n)/n, cumsum(d)/sum(x), xlab= "t", ylab="TTT")
abline(0,1)
```